//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso_DBFirst.Models
{
   using System;
   using System.Collections.Generic;

   //mo¿na korzystaæ z obu zapisów
   //public enum Grade : int   {      A = 0,      B = 1,      C = 2,      D = 3,      F = 4   }
   public enum Grade { A,B,C,D,F }

   public partial class Enrollment
   {
      public int EnrollmentID { get; set; }
      public int CourseID { get; set; }
      public int StudentID { get; set; }
      public Nullable<Grade> Grade { get; set; }

      public virtual Course Course { get; set; }
      public virtual Student Student { get; set; }
   }
}
