//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso_DBFirst.Models
{
    using System;
    
    public enum Grade : int
    {
        A = 0,
        B = 1,
        C = 2,
        D = 3,
        F = 4
    }
}
